# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-05 21:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20160602_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_title',
            field=models.SlugField(unique=True),
        ),
    ]
