# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-09 01:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_remove_album_audio_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='video',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
