# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-10 00:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0009_album_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.FileField(default='', upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='album',
            name='logo',
        ),
    ]
