# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-10 05:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0010_auto_20160809_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='logo',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
