# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-10 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0011_album_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='logo',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
