# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-10 17:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0012_song_logo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='album_logo',
            new_name='album_art',
        ),
        migrations.RemoveField(
            model_name='album',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='song',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='song',
            name='video',
        ),
    ]
