# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-11 21:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0014_auto_20160811_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='audio_file',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
