# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-12 17:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0015_album_audio_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='audio_file',
        ),
    ]
