# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-12 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0016_remove_album_audio_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_title',
            field=models.CharField(max_length=250),
        ),
    ]
